name: desireobtaincherish
favicon: null
layout_spectrum: 0.25813
typography_spectrum: 0.556786298751831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
